### PR TITLE
New feature - report gpu memory

### PR DESCRIPTION
**Pull request by miquelmassot**
Add a new plugin to report used GB/ total GB of VRAM in all GPUs (summed).

### CODE REVIEW

**Comment by 2KAbhishek** [comment]
@miquelmassot thanks a lot for this PR, can you please attach some screenshots for ref as well!

**Comment by miquelmassot** [comment]
image

Hi!

my idea was to report GPU memory alongside GPU usage. However, I have not been able to write to the status bar. This is how far I got.

**Comment by 2KAbhishek** [comment]
Thanks, I'll work on this as soon as I get time

**Review by 2KAbhishek — APPROVED** [review]

**Comment by 2KAbhishek** [comment]
The code is very similar to the existing script, will be enhancing that instead of adding a new one, please let me know if you want to contribute there, closing this till then

**Pull request closed without merging**
